### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by yeungmozhu** [alpertunga-bile/prompt-generator-comfyui#11]
**Describe the bug**
 [Errno 22] Invalid argument
use basicWorkflowWithPromptGenerator.json workflow, error when running to Prompt Generator node

**To Reproduce**
Use basicWorkflowWithPromptGenerator.json workflow, error when running to Prompt Generator node

**Code**
Traceback (most recent call last):
  File "D:\SDLocal\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\SDLocal\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\SDLocal\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\SDLocal\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt-generator-comfyui\prompt_generator.py", line 284, in generate
    self._generated_prompts = get_generated_texts(
  File "D:\SDLocal\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt-generator-comfyui\generator\generate.py", line 106, in get_generated_texts
    generated_text = preprocess(prompt + result, preprocess_mode)
  File "D:\SDLocal\ComfyUI_windows_portable\python_embeded\lib\site-packages\preprocess.py", line 363, in preprocess
    contentType = registry.getContentType(infile)
  File "D:\SDLocal\ComfyUI_windows_portable\python_embeded\lib\site-packages\preprocess.py", line 803, in getContentType
    content = open(path, 'rb').read()
OSError: [Errno 22] Invalid argument: '((masterpiece, best quality, ultra detailed)), illustration, digital art, 1girl, solo, ((stunningly beautiful)), ((upper body portrait)), by Stanley Artgerm Lau, (by Loimu), nami  with black hair and blue eye makeup mernie (honkai star rail yuuutsu ), smile\n'

**Operating System**
Windows

** Python Version**
Python version: 3.10.9 

** Transformers and optimum packages versions **
transformers-4.39.2
optimum-1.18.0

**Comment by alpertunga-bile** [comment]
Hello, thanks for reporting. I have added updates. Please update the node and let me know if the issue is going on.

**Comment by yeungmozhu** [comment]
Thank you for fixing this so quickly!
